version: "3.7"
services:
  kong:
    container_name: kong
    restart: always
    image: kong:latest
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8544 ssl
    ports:
      - "8000:8000"
      - "8543:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8544:8544"
  mongo-users:
    container_name: mongo-users
    restart: always
    environment:
      MONGO_INITDB_DATABASE: Animals-auth
    image: mongo
  api:
    container_name: api
    build:
      context: ./API
      dockerfile: ./Dockerfile
    restart: always
#    links:
#      - graphdb
    networks:
      default:
        aliases:
          - front-end-animals
  auth:
    container_name: auth
    build:
      context: ./autenticacao
      dockerfile: ./Dockerfile
    restart: always
    links:
      - mongo-users
    networks:
      default:
        aliases:
          - auth
  front-end-animals:
    container_name: front-end-animals
    restart: always
    build:
      context: ./frontend/animals
      dockerfile: ./Dockerfile
    ports:
      - "12080:80"
    links:
      - kong
      - api
      - auth
      - mongo-users
#      - graphdb
    networks:
      default:
        aliases:
          - auth
#  graphdb:
#    container_name: graphdb
#    image: khaller/graphdb-free:9.10.0
#    #image: zzglider/clav-graphdb:1.0.0
#    #image: zzglider/mygraphdb:prc2021
#    build:
#      context: ./graphdb
#      dockerfile: ./Dockerfile
#    restart: always
#    ports:
#      - "9200:7200"